
export enum dogsActionsTypes {
	GET_ALL_BREEDS = "GET_ALL_BREEDS",
	SEARCH_DOGS = "SEARCH_DOGS",
	GET_DOGS_SUCCESS = "GET_DOGS_SUCCESS",
	GET_DOGS_ERROR = "GET_DOGS_ERROR",
	ADD_TO_LIKED = "ADD_TO_LIKED"
}
